Added navigation view and toolbar close button to info sheet
wtg/Shuttle-Tracker-SwiftUI-2.0 pull request #51
Opened 2021-12-05 03:33 UTC by emanua

![IMG_181CDF5B000B-1](https://user-images.githubusercontent.com/42878286/144732341-87d5372e-9c37-49b5-83fe-ecb702a1f5cb.jpeg)

Closes #50

2021-12-05 04:06 UTC, Gerzer requested changes
Aside from the extraneous preprocessor conditional about which I commented, everything looks good!

2021-12-05 04:06 UTC, Gerzer commented on iOS/Views/InfoSheet.swift
> +				#endif // !os(macOS)
`InfoSheet` isn’t compiled when building for macOS, so the `#if !os(macOS)`/`#endif` preprocessor conditional shouldn’t be necessary here.

2021-12-05 21:37 UTC, emanua commented on iOS/Views/InfoSheet.swift
> +				#endif // !os(macOS)
Good point, I removed the conditional. Thanks!

2021-12-07 03:07 UTC, Gerzer approved these changes

2021-12-07 03:08 UTC, merged